Feature - Exception handler
Avaiga/taipy-rest pull request #77
Opened 2022-08-10 10:38 UTC by khaitruong922

Raise taipy.core exceptions whenever an entity or config not found. Add error handler to handle each exception.

2022-08-10 14:15 UTC, FabienLelaquais requested changes
Please elaborate on these get_or_raise.
I suspect a local, private _get() would be enough everywhere.

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/error_handler.py
> +def handle_data_node_not_found(e):
Hum. 
When I see a piece of code used more than three times, I tend to make that a function.

What about a:
```
def _create_404(e: Exception) -> Tuple
  return jsonify({"message": e.message}), 404
```

then, ten times, you would `return _create_404(e)`

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/cycle.py
> +    """Raise an exception if the data node does not exist."""
So I don't understand the 'return' statement.

I suspect the function signature and doc are wrong.

Do you really plan to publish this function anyway?

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/datanode.py
> +    """Raise an exception if the data node does not exist."""
Same here: this function MAY return something valid.
And it's probably a private function. (-> `_get(id: str) -> DataNode`)

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/datanode.py
> +        return {"message": f"Data node {datanode_id} deleted."}
"Data node {datanode_id} deleted."
->
"Data node {datanode_id} was deleted."

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/job.py
> +        return {"message": f"Job {job_id} deleted."}
was deleted

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/job.py
> +            "message": "Job created.",
was created

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/pipeline.py
> +            "message": "Pipeline created.",
was created

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/scenario.py
> +        return {"message": f"Scenario {scenario_id} deleted."}
was

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/scenario.py
> +            "message": "Scenario created.",
was

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/task.py
> +        return {"message": f"Task {task_id} deleted."}
was

2022-08-10 14:15 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/task.py
> +            "message": "Task created.",
was

2022-08-17 16:12 UTC, FabienLelaquais approved these changes, later dismissed
Tiny tiny comments on the form.

2022-08-17 16:12 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/cycle.py
> +                    'message': 'cycle was created.',
Capitalize sentence.

2022-08-17 16:12 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/job.py
>          return {"message": f"Cancelled job {job_id}"}
Check if this should be worded just like the other message: (only one 'l' by the way)

     Job {} was canceled.

2022-08-17 16:12 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/pipeline.py
> +        return {"message": f"Executed pipeline {pipeline_id}"}
Same here:

Pipeline {} was executed.

(or submitted? what is the difference? asynchronism I suspect)

2022-08-17 16:12 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/scenario.py
> +        return {"message": f"Executed scenario {scenario_id}"}
See similar comment on Pipelines...

2022-08-17 16:12 UTC, FabienLelaquais commented on src/taipy/rest/api/resources/task.py
>          return {"message": f"Executed task {task_id}"}
Check here please

2022-08-18 06:54 UTC, jrobinAV approved these changes

2022-08-18 06:56 UTC, jrobinAV reviewed
Tests are broken

2022-08-18 08:22 UTC, khaitruong922 commented
Tests will not be broken anymore after the fix to taipy-core

2022-08-18 08:22 UTC, merged